
async function getMealPlan(){
    try{
        console.log('prueba');
    }catch(err){
        console.log('error:' + err);
        
    }
}


